export const ADD_CAT = 'CAT/ADD_CAT'
export const LIST_CATS = 'CAT/LIST_CATS'
export const DELETE_CAT = 'CAT/DELETE_CAT'
export const UPDATE_CAT = 'CAT/UPDATE_CAT'
export const LIST_CAT_BRAND = 'CAT/LIST_CAT_BRAND'
