export const ADD_TO_CART = 'CART/ADD_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'CART/REMOVE_PRODUCT_FROM_CART'
export const UPDATE_QTY_CART = 'CART/REMOVE_PRODUCT_FROM_CART'
export const CART = 'CART/CART'

export const ADD_ORDER = 'CART/ADD_ORDER'
export const GET_ORDERS = 'CART/GET_ORDERS'
export const GET_ORDER = 'CART/GET_ORDER'
export const UPDATE_ORDER = 'CART/UPDATE_ORDER'
