export const ADD_IMAGE = 'IMAGE/ADD_IMAGE'
export const LIST_IMAGES = 'IMAGE/LIST_IMAGES'
export const DELETE_IMAGE = 'IMAGE/DELETE_IMAGE'
export const LIST_IMAGES_BY_PRODUCT_ID = 'IMAGE/LIST_IMAGES_BY_PRODUCT_ID'
