export const ADD_TAG = 'TAG/ADD_TAG'
export const LIST_TAGS = 'TAG/LIST_TAGS'
export const LIST_TAGS_FOR_MENU = 'TAG/LIST_TAGS_FOR_MENU'
export const LIST_TAG_BRANDS = 'TAG/LIST_TAG_BRANDS'
export const DELETE_TAG = 'TAG/DELETE_TAG'
export const UPDATE_TAG = 'TAG/UPDATE_TAG'
